### ISSUE TITLE
Can't install Digitransit.fi Geocoder plugin to QGIS

### ISSUE THREAD

**Issue by joonaris** [GispoCoding/QGISDigitransitGeocoding#19] opened 2022-08-17 08:42 UTC
When i try to install the plugin i get following error message:

Lisäosaa 'QGISDigitransitGeocoding-master' ei voitu ladata due to an error when calling its classFactory() method 

_TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python/plugins\QGISDigitransitGeocoding-master\__init__.py", line 27, in classFactory
    return DigitransitGeocoder(iface)
  File "C:\Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python/plugins\QGISDigitransitGeocoding-master\digitransit_geocoder.py", line 44, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python-versio: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGISin versio: 3.22.7-Białowieża Białowieża, 5a65627a 

Python-polku:
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python
C:/Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python
C:/Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python/plugins
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.7\bin\python39.zip
C:\PROGRA~1\QGIS32~1.7\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib
C:\Program Files\QGIS 3.22.7\bin
C:\Users\Joona\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python
.
C:\Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\Kuntatyötila/python/plugins\qgis_resource_sharing
C:\Users\Joona\AppData\Roaming\QGIS\QGIS3\profiles\Kuntatyötila\python\plugins\qgis_resource_sharing
C:\Users\Joona\AppData\Roaming\QGIS\QGIS3\profiles\Kuntatyötila\python\plugins\qgis_resource_sharing\ext_libs_
**Describe the bug**

![image](https://user-images.githubusercontent.com/104818918/185075090-419e7f7b-d6ac-4c6a-a5e3-95b056536cda.png)

**Comment by JuhoErvasti** [comment] 2023-12-15 08:25
The code in the error message has been since changed to a wholly different format and the issue can't seem to be reproduced, so I'll close this issue and let's reopen if more issues arise.

**Closed as completed by JuhoErvasti** 2023-12-15 08:25 UTC
Labels: bug
